### PR TITLE
ids now have 5 digits, extend width

### PR DESCRIPTION
**Pull request by saerdnaer**
Some conferences e.g. 35C3 now arrived at 5 digit ids... Already deployed on tracker.c3voc.de

### CODE REVIEW

**Comment by jjeising** [comment]
Hey @saerdnaer did you have time to check back on this pull request?

**Comment by saerdnaer** [comment]
@jjeising We have to modify https://tracker.c3voc.de/images/main.png as the yellow image is part of the image – but I can not find the corresponding source files in this repo...

**Comment by jjeising** [comment]
Yes, removing this image is a medium term goal, but i think this should be beyond the scope of this pull request.

What should be the new width, in pixels (@1x)?

**Comment by saerdnaer** [comment]
@jjeising:
Here is a screenshot from my laptop and some mockup  – I am not shure if the resolution is @1 and how to properly measure the pixels...

https://tracker.c3voc.de/camp19/tickets
image

messung

**Pull request closed without merging**
